// <auto-generated />
using System;
using ChatBirthdayBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatBirthdayBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240410041553_AddSentMessagesAndSetMaxStringLength")]
    partial class AddSentMessagesAndSetMaxStringLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ChatBirthdayBot.Database.ChatRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<byte>("CustomOffsetInHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldPinNotify")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("TimeZoneHourOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.SentMessage", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SendDateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "MessageId");

                    b.ToTable("SentMessages");
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.UserChat", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.UserRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<byte?>("BirthdayDay")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("BirthdayMonth")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("BirthdayYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.SentMessage", b =>
                {
                    b.HasOne("ChatBirthdayBot.Database.ChatRecord", "Chat")
                        .WithMany("SentMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.UserChat", b =>
                {
                    b.HasOne("ChatBirthdayBot.Database.ChatRecord", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBirthdayBot.Database.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatBirthdayBot.Database.ChatRecord", b =>
                {
                    b.Navigation("SentMessages");

                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
