//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBirthdayBot.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lines {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lines() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChatBirthdayBot.Localization.Lines", typeof(Lines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BirthdayDate {
            get {
                return ResourceManager.GetString("BirthdayDate", resourceCulture);
            }
        }
        
        internal static string BirthdayNotSet {
            get {
                return ResourceManager.GetString("BirthdayNotSet", resourceCulture);
            }
        }
        
        internal static string BirthdayRemoved {
            get {
                return ResourceManager.GetString("BirthdayRemoved", resourceCulture);
            }
        }
        
        internal static string BirthdaySetFailed {
            get {
                return ResourceManager.GetString("BirthdaySetFailed", resourceCulture);
            }
        }
        
        internal static string BirthdaySetSuccessfully {
            get {
                return ResourceManager.GetString("BirthdaySetSuccessfully", resourceCulture);
            }
        }
        
        internal static string BirthdayMessage {
            get {
                return ResourceManager.GetString("BirthdayMessage", resourceCulture);
            }
        }
        
        internal static string NoBirthdays {
            get {
                return ResourceManager.GetString("NoBirthdays", resourceCulture);
            }
        }
        
        internal static string BirthdaysCommandDescription {
            get {
                return ResourceManager.GetString("BirthdaysCommandDescription", resourceCulture);
            }
        }
        
        internal static string BirthdayCommandDescription {
            get {
                return ResourceManager.GetString("BirthdayCommandDescription", resourceCulture);
            }
        }
        
        internal static string SetBirthdayCommandDescription {
            get {
                return ResourceManager.GetString("SetBirthdayCommandDescription", resourceCulture);
            }
        }
        
        internal static string RemoveBirthdayCommandDescription {
            get {
                return ResourceManager.GetString("RemoveBirthdayCommandDescription", resourceCulture);
            }
        }
    }
}
