//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBirthdayBot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBirthdayBot.Localization.Lines", typeof(Lines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday is set on {0}. If this is incorrect, please correct it by using the &lt;code&gt;/setbirthday &amp;lt;DD-MM-YYYY&amp;gt;&lt;/code&gt; command. Or if you don&apos;t want to set your birthday year, just use the &lt;code&gt;&amp;lt;DD-MM&amp;gt;&lt;/code&gt; format. To remove it from the database, use the &lt;code&gt;/removebirthday&lt;/code&gt; command..
        /// </summary>
        internal static string BirthdayDate {
            get {
                return ResourceManager.GetString("BirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday is currently not set. You can set it by using &lt;code&gt;/setbirthday &amp;lt;DD-MM-YYYY&amp;gt;&lt;/code&gt; command. If you don&apos;t want to set your birthday year, just use the &lt;code&gt;&amp;lt;DD-MM&amp;gt;&lt;/code&gt; format..
        /// </summary>
        internal static string BirthdayNotSet {
            get {
                return ResourceManager.GetString("BirthdayNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday is removed from the database..
        /// </summary>
        internal static string BirthdayRemoved {
            get {
                return ResourceManager.GetString("BirthdayRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an incorrect date (or format). Please use the command followed by a correct date..
        /// </summary>
        internal static string BirthdaySetFailed {
            get {
                return ResourceManager.GetString("BirthdaySetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday has been successfully added to the database!.
        /// </summary>
        internal static string BirthdaySetSuccessfully {
            get {
                return ResourceManager.GetString("BirthdaySetSuccessfully", resourceCulture);
            }
        }
    }
}
